version: "3.3"

#====================#
#      Services      #
#====================#
services:

  #=====================#
  #       Grafana       #
  #=====================#
  grafana:
    image: grafana/grafana:8.5.6
    restart: unless-stopped
    ports:
      - "3030:3000"
    volumes:
      - grafanaData:/var/lib/grafana
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini

  #=====================#
  #       Influx       #
  #=====================#
  influxdb:
    image: influxdb:latest
    restart: unless-stopped
    ports:
      - "8086:8086"
    volumes:
      - influxData:var/lib/influxdb2
      - ./influx/config.yml:/etc/influxdb2/config.yml

  #=====================#
  #       Telegraf       #
  #=====================#
  telegraf:
    image: telegraf:latest
    restart: unless-stopped
    ports:
      - "8092:8092"
      - "8094:8094"
      - "8125:8125"
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf
    depends_on:
      - influxdb

  #=================================#
  #      Mosquitto MQTT Broker      #
  #=================================#
  mosquitto:
    image: eclipse-mosquitto:1.6.15
    restart: unless-stopped
    ports:
      - "1883:1883"
    volumes:
      - mosquittoLog:/mosquitto/log
      - mosquittoData:/mosquitto/data

  #=================================#
  #            Node Red             #
  #=================================#
  nodered:
    build: ./nodered
    image: nodered/node-red:latest
    restart: unless-stopped
    ports:
      - "1880:1880"
    volumes:
      - noderedData:/data
      - ./nodered/defaultFlows:/data/lib/flows


#====================#
#      Volumnes      #
#====================#
volumes:
  grafanaData:
  noderedData:
  mosquittoLog:
  mosquittoData:
  influxData:

