version: "3.3"

#====================#
#      Services      #
#====================#
services:
  #=====================#
  #       WebApp        #
  #=====================#
  webapplication:
    build: ./webapplication
    container_name: webapplication
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - webapplicationData:/data
      - ./webapplication:/var/www/html/
    networks:
      - edge


  #=====================#
  #    elasticsearch    #
  #=====================#
  elasticsearch:
    build: ./elasticsearch
    image: comworkio/elasticsearch:7.16.1-1.13-arm
    container_name: elasticsearch
    restart: unless-stopped
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearchData:/var/lib/elasticsearch
    networks:
      - edge

#  #=====================#
#  #       kibana        #
#  #=====================#
#  kibana:
#    build: ./kibana
#    image: comworkio/kibana:7.16.1-1.13-arm
#    container_name: kibana
#    ports:
#      - "5601:5601"
#    environment:
#      - ES_PROTO=http
#      - ES_HOST=elasticsearch
#      - ES_PORT=9200
#    volumes:
#      - kibanaData:/var/lib/kibana
#    networks:
#      - edge
#    depends_on:
#      - elasticsearch

  #=====================#
  #       Grafana       #
  #=====================#
  grafana:
    image: grafana/grafana:8.5.6
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3030:3000"
    volumes:
      - grafanaData:/var/lib/grafana
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
    networks:
      - edge



  #=================================#
  #      Mosquitto MQTT Broker      #
  #=================================#
  mosquitto:
    image: eclipse-mosquitto:1.6.15
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "8883:1883"
      - "9001:9001"
    volumes:
      - mosquittoLog:/mosquitto/log
      - mosquittoData:/mosquitto/data
    networks:
      - edge

  #=================================#
  #            Node Red             #
  #=================================#
  nodered:
    build: ./nodered
    image: nodered/node-red:latest
    container_name: nodered
    restart: unless-stopped
    ports:
      - "1880:1880"
    volumes:
      - noderedData:/data
      - ./nodered/dataFaker.json:/data/lib/flows/dataFaker.json
    networks:
      - edge



#====================#
#      Volumnes      #
#====================#
volumes:
  grafanaData:
  noderedData:
  elasticsearchData:
  kibanaData:
  mosquittoLog:
  mosquittoData:
  webapplicationData:

#====================#
#      Networks      #
#====================#
networks:
  edge:
