version: "3.3"

#====================#
#      Services      #
#====================#
services:
  #=====================#
  #       WebApp        #
  #=====================#
  application:
    build: ./application
    container_name: application
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./application:/var/www/html/
    networks:
      - edge


  #=====================#
  #    elasticsearch    #
  #=====================#
  elasticsearch:
    build: ./elasticsearch
    image: comworkio/elasticsearch:7.16.1-1.13-arm
    container_name: elasticsearch
    restart: unless-stopped
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearchData:/var/lib/elasticsearch
    networks:
      - edge

  #=====================#
  #       Grafana       #
  #=====================#
  grafana:
    build: ./grafana
    image: grafana/grafana:7.5.16
    #    image: localbuild/grafana:april2021
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3030:3000"
    volumes:
      - grafanaData:/var/lib/grafana
    networks:
      - edge

  #=================================#
  # Composer PHP Dependency Manager #
  #=================================#
  composer:
    container_name: composer
    image: composer:latest
    command: [ "composer", "install" ]
    volumes:
      - ./application/assets/composer:/var/www/html/assets/composer
    working_dir: /var/www/html/assets/composer
    networks:
      - edge

  #=================================#
  #      Mosquitto MQTT Broker      #
  #=================================#
  mosquitto:
    build: ./mosquitto
    image: eclipse-mosquitto:1.6.14
#    image: localbuild/mosquitto:april2021
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "8883:1883"
      - "9001:9001"
    volumes:
      - mosquittoLog:/mosquitto/log
      - mosquittoData:/mosquitto/data
    networks:
      - edge

  #=================================#
  #            Node Red             #
  #=================================#
  nodered:
    build: ./nodered
    image: nodered/node-red:latest
    #    image: localbuild/nodered:april2021
    container_name: nodered
    restart: unless-stopped
    ports:
      - "1880:1880"
    volumes:
      - noderedData:/data
    networks:
      - edge


#====================#
#      Volumnes      #
#====================#
volumes:
  grafanaData:
  noderedData:
  elasticsearchData:
  mosquittoLog:
  mosquittoData:
  applicationData:

#====================#
#      Networks      #
#====================#
networks:
  edge:
